from django.contrib import admin

# Register your models here.

from .models import *

admin.site.register(AboutChemicalFertilizer)
admin.site.register(AboutDisease)
admin.site.register(AboutFieldPreparation)
admin.site.register(AboutNutrientDeficiency)
admin.site.register(AboutOrganicManure)
admin.site.register(AboutPest)
admin.site.register(AboutRodent)
admin.site.register(AboutSoil)
admin.site.register(AboutWeed)
admin.site.register(Admin)
admin.site.register(AuthGroup)
admin.site.register(AuthGroupPermissions)
admin.site.register(AuthPermission)
admin.site.register(AuthUser)
admin.site.register(AuthUserGroups)
admin.site.register(AuthUserUserPermissions)
admin.site.register(ChemicalFertilizer)

admin.site.register(Climate)
admin.site.register(Crop)
admin.site.register(CropPattern)
admin.site.register(Disease)
admin.site.register(DjangoAdminLog)
admin.site.register(DjangoContentType)
admin.site.register(DjangoMigrations)
admin.site.register(DjangoSession)
admin.site.register(FieldPreparation)
admin.site.register(NotificationData)
admin.site.register(NutrientDeficiency)
admin.site.register(OrganicManure)
admin.site.register(Pest)
admin.site.register(PortalCoreUsers)
admin.site.register(Rodent)
admin.site.register(Soil)
admin.site.register(UserInfo)
admin.site.register(VarietiesInState)
admin.site.register(Variety)
admin.site.register(Weed)
